### ISSUE TITLE
ext libraries can't be imported

### ISSUE THREAD

**Issue by ghost** [hayatoy/cloudml-magic#9]
I put 'install_requires' dict under "%ml_init" but I got error in logging of ML engine.

<Notebook>
%ml_init -projectId <PROJECTID> -bucket <BUCKET> -scaleTier BASIC  
{'install_requires': ['google-cloud-storage']}

%%ml_code
import tensorflow as tf
from sklearn import model_selection
import logging
from google.cloud import storage

<Error message>
Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 5, in <module> import google.cloud.storage ImportError: No module named storage

**Comment by hayatoy** [comment]
Hi @nobmizue
It must be same as issue #5 ,
Jupyter Notebook doesn’t recognize ml_init command as a cell command when you type `%ml_init`.
Replace it to `%%ml_init` (double %), so it must be ok.
FYI, You don’t need to modify when you use Datalab, since it automatically generates an alias of cell/line magic.

**Comment by hayatoy** [comment]
Close due to inactivity.
